// Mocks generated by Mockito 5.4.6 from annotations
// in cashier_app/test/features/cash_drawer/presentation/state/cash_drawer_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cashier_app/features/cash_drawer/domain/entities/cash_drawer_session.dart'
    as _i4;
import 'package:cashier_app/features/cash_drawer/domain/repositories/cash_drawer_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CashDrawerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCashDrawerRepository extends _i1.Mock
    implements _i2.CashDrawerRepository {
  @override
  _i3.Future<int> openSession(_i4.CashDrawerSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #openSession,
          [session],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> closeSession(
    int? id,
    _i4.CashDrawerSession? session,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #closeSession,
          [
            id,
            session,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.CashDrawerSession?> getActiveSession() => (super.noSuchMethod(
        Invocation.method(
          #getActiveSession,
          [],
        ),
        returnValue: _i3.Future<_i4.CashDrawerSession?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.CashDrawerSession?>.value(),
      ) as _i3.Future<_i4.CashDrawerSession?>);

  @override
  _i3.Future<List<_i4.CashDrawerSession>> getAllSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSessions,
          [],
        ),
        returnValue: _i3.Future<List<_i4.CashDrawerSession>>.value(
            <_i4.CashDrawerSession>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.CashDrawerSession>>.value(
                <_i4.CashDrawerSession>[]),
      ) as _i3.Future<List<_i4.CashDrawerSession>>);
}
